# Generated by Django 5.2 on 2025-09-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologia', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
